### ISSUE TITLE
Piping binary readable stream into a document

### ISSUE THREAD

**Issue by aleclarson** [neumino/rethinkdbdash-examples#1]
I'm interested in taking a `ReadableStream` and piping it into the field of a specific document.

Is this possible? If not, what are my options?

Relevant reading: https://github.com/rethinkdb/rethinkdb/issues/137

### Use Case

```js
const db = rethinkdb();
const app = express();
app.use((req, res) => {
  // req.pipe(db.table('photos').something)
});
```

**Comment by aleclarson** [comment]
Ooh, it would be nice if I could just plop the `ReadableStream` in the `insert` query.

```js
const promise = db.table('photos').insert({ id: 0, file: req }).run();
```

The returned `promise` resolves:
- after the document is inserted
- before the `ReadableStream` finishes

To know if the `ReadableStream` has finished or failed:

```js
req.on('end', onFinish);
req.on('error', onError);
```

**Comment by aleclarson** [comment]
Is using `regrid` recommended? https://github.com/internalfx/regrid

**Comment by neumino** [comment]
You can't pipe a stream into a single document. This is fundamentally impossible the way the protocol under the hood is designed.

I've never used regrid, but it's probably one solution.
